|-> error(message, exitCode?) {
    print("Error!")
    print(message)
    print(__CALL_STACK)
    process.exit(exitCode ! 5)
}